---
- name: Access remote machine, Create /home/details_app/, Clone /home/details_app/ 
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Block for Rocky-based tasks
      when: ansible_os_family == "Rocky"
      block:
      - name: Install git (for Rocky Linux based systems)
        dnf:
          name:
            - git
            - acl
            - python3
            - python3-pip
          state: present
          update_cache: yes

      - name: Install pipenv python package
        ansible.builtin.pip:
          name: pipenv

      - name: Add user details_app
        ansible.builtin.user:
          name: details_app
          password: "{{ '123456' | password_hash('sha512') }}"
          shell: /bin/bash
          groups: docker
          create_home: yes

      - name: git clone /home/details_app/ on each server AS details_app
        git:
          repo: https://github.com/devopsevgeny/detailsapp.git
          dest: /home/details_app/detailsapp
        become_user: details_app

      - name: Install application dependencies with pipenv
        ansible.builtin.shell:
          cmd: /usr/local/bin/pipenv --python /usr/bin/python3 install --deploy 
          chdir: /home/details_app/detailsapp          
        become_user: details_app

      - name: Run app inside pipenv
        ansible.builtin.shell:
          cmd: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            bash
            uv self update
            uv python install 3.11
            uv python pin 3.11
            pipenv install
            pipenv shell
            python details.py
          chdir: /home/details_app/detailsapp          
        become_user: details_app